[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solwin = "86u5wfDu5bpzVDujCMuHNuJtyicEnnkkiibEuwEfYSSf"

[programs.localnet]
solwin = "6EBNXWifHe8goCKF6ARu3FXTQUMvAcwwrcNwMwTDjhX5"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/WebstormProjects/solana-program-library/owner.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
